communications/urls.py
from django.conf.urls import patterns, url
from .views import comm_details, comm_creation


com_urls = patterns('',
                    url(r'^$', comm_details,
                        name='comm_detail'
                        ),
                    url(r'^/edit$', comm_creation,
                        name='comm_update'
                        ),
                    )

crmapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import logout

from custom_login.views import custom_login

from marketing.views import home_page

from subscribers.views import subscriber_view

from accounts.urls import account_urls

from contacts.urls import contact_urls
from contacts.views import cont_creation, ContactDelete

from communications.urls import com_urls
from communications.views import comm_creation, CommDelete


urlpatterns = patterns('',

                       # Admin URL
                       url(r'^admin/',
                           include(admin.site.urls)
                           ),

                       # Marketing pages
                       url(r'^$',
                           home_page,
                           name="home"
                           ),

                       # Subscriber related URLs
                       url(r'^signup/',
                           subscriber_view,
                           name='signup_url'
                           ),

                       # Login/Logout URLs
                       url(r'^login/$',
                           custom_login,
                           {'template_name': 'login.html'},
                           name="custom_login",
                           ),
                       url(r'^logout/$',
                           logout,
                           {'next_page': '/login/'}
                           ),

                       # Account related URLs
                       url(r'^account/',
                           include(account_urls)
                           ),

                       # Contact related URLS
                       url(r'^contact/new/$',
                           cont_creation,
                           name='contact_new'
                           ),
                       url(r'^contact/(?P<uuid>[\w-]+)/', include(contact_urls)
                           ),

                       url(r'^contact/(?P<pk>[\w-]+)/delete/$',
                           ContactDelete.as_view(),
                           name='contact_delete'
                           ),

                       # Communication related URLs
                       url(r'^comm/new/$',
                           comm_creation,
                           name='comm_new'
                           ),
                       url(r'^comm/(?P<pk>[\w-]+)/delete/$',
                           CommDelete.as_view(), name='comm_delete'
                           ),
                       url(r'^comm/(?P<uuid>[\w-]+)',
                           include(com_urls)
                           ),

                       )

communications/models.py
from django.db import models
from django.contrib.auth.models import User

from accounts.models import Account

from shortuuidfield import ShortUUIDField


class Communication(models.Model):
    uuid = ShortUUIDField(unique=True)
    TYPE_LIST = ((1, 'Meeting'),
                 (2, 'Phone'),
                 (3, 'Email'),
                 )

    subject = models.CharField(max_length=50)
    notes = models.TextField()
    kind = models.PositiveSmallIntegerField(choices=TYPE_LIST)
    date = models.DateField()
    owner = models.ForeignKey(User)
    account = models.ForeignKey(Account)
    created_on = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'communications'

    def __unicode__(self):
        return u"%s" % self.subject

    @models.permalink
    def get_absolute_url(self):
        return 'comm_detail', [self.uuid]

    @models.permalink
    def get_update_url(self):
        return 'comm_update', [self.uuid]

    @models.permalink
    def get_delete_url(self):
        return 'comm_delete', [self.id]

communications/forms.py
from django import forms

from .models import Communication


class CommunicationForm(forms.ModelForm):
    class Meta:
        model = Communication
        fields = ('subject', 'notes', 'kind', 'date', 'account',)
        widgets = {
            'subject': forms.TextInput(
                attrs={
                    'placeholder': 'Subject',
                    'class': 'form-control'
                }
            ),
            'notes': forms.Textarea(
                attrs={
                    'placeholder': 'Add notes',
                    'class': 'form-control'
                }
            ),
            'kind': forms.Select(
                attrs={
                    'placeholder': 'Type',
                    'class': 'form-control'
                }
            ),
            'date': forms.DateInput(
                attrs={
                    'placeholder': 'Date',
                    'class': 'form-control'
                }
            ),
        }

communications/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, Http404
from django.utils.decorators import method_decorator
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse
# from django.core.urlresolvers import reverse

from .forms import CommunicationForm
from accounts.models import Account
from .models import Communication


@login_required
def comm_details(request, uuid):

    comm = Communication.objects.get(uuid=uuid)
    if comm.owner != request.user:
            return HttpResponseForbidden()
    return render(request, 'communications/comm_detail.html', {'comm': comm})


@login_required
def comm_creation(request, uuid=None, account=None):

    if uuid:
        comm = get_object_or_404(Communication, uuid=uuid)
        if comm.owner != request.user:
            return HttpResponseForbidden()
    else:
        comm = Communication(owner=request.user)

    if request.POST:
        form = CommunicationForm(request.POST, instance=comm)

        if form.is_valid():
            # make sure the user owns the account
            account = form.cleaned_data['account']

            if account.owner != request.user:
                return HttpResponseForbidden()
            # save the data
            comm = form.save(commit=False)
            comm.owner = request.user
            comm.save()
            if request.is_ajax():
                return render(request,
                              'communications/comm_item_view.html',
                              {'comm': comm, 'account': account}
                              )

            # return the user to the account detail view
            else:
                reverse_url = reverse('account_detail', args=(account.uuid,))
                return redirect(reverse_url)
        else:
            account = form.cleaned_data['account']

    else:
        form = CommunicationForm(instance=comm)
    acc_id = request.GET.get('account', '')

    if acc_id:
        account = Account.objects.get(id=acc_id)

    template_vars = {
        'form': form,
        'comm': comm,
        'account': account
    }
    if request.is_ajax():
        template_name = 'communications/comm_item_form.html'
    else:
        template_name = 'communications/comm_creation.html'

    return render(request, template_name, template_vars)


class CommMixin(object):
    model = Communication

    def get_context_data(self, **kwargs):
        kwargs.update({'object_name': 'Communication'})
        return kwargs

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CommMixin, self).dispatch(*args, **kwargs)


class CommDelete(CommMixin, DeleteView):
    template_name = 'object_confirm_delete.html'

    def get_object(self, queryset=None):
        obj = super(CommDelete, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        account = Account.objects.get(id=obj.account.id)
        self.account = account
        return obj

    def get_success_url(self):
        return reverse(
            'account_detail',
            args=(self.account.uuid,)
        )

templates/communications/comm_creation.html
{% extends 'base.html' %}
{% block title %}Communication Operation{% endblock title %}

{% block content %}
    <div id="content-container" class="container p-none">
        <h4 class="ad-mh">Add a Communication</h4>
        {% include 'communications/comm_item_form.html' %}
    </div>
{% endblock content %}

templates/communications/comm_detail.html
{% extends 'base.html' %}
{% block title %}Communication Detail{% endblock title %}

{% block content %}
    <div id="content-container" class="container p-none">
        <ul id="co-list" class="strip-list col-md-12 p-none">
            {% include 'communications/comm_item_view.html' %}
        </ul>
    </div>
{% endblock %}

templates/communications/comm_item_form.html
<form id="comm-form"
      {# POST Destination #}
      action="{% if comm.uuid %}
              {% url 'comm_update' comm.uuid %}
              {% else %}
              {% url 'comm_new' %}
              {% endif %}"
      method="post">
    {% csrf_token %}
    <p>{{ form.subject }}</p>
    <div id="comm-form">
        <p>{{ form.subject.errors }}</p>
        <p>{{ form.notes }}</p>
        <p>{{ form.notes.errors }}</p>
        <table class="table comm-form">
            <tbody>
                <tr>
                    <td>{{ form.kind }}</td>
                    <td>{{ form.date }}</td>
                    <td class="comm-submit-td">
                        <input class="btn btn-success comm-submit"
                               type="submit" value="SAVE"/></td>
                </tr>
                <tr>
                    <td>{{ form.kind.errors }}</td>
                    <td>{{ form.date.errors }}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>

    <input id="id_account" name="account"
           type="hidden"
           value="{% if request.GET.account %}
           {{ request.GET.account }}{% else %}{{ account.id }}{% endif %}"/>
    <input id="id_owner" name="owner" type="hidden" value="{{ user.username }}"/>
</form>

templates/communications/comm_item_view.html
<li class="co-item">
    <h5 class="co-item-h">{{ comm.subject }}
        <span>
            {# Comm Delete URL #}
            <a class="cancel comm-control" 
               href="{% url 'comm_delete' comm.id %}?account={{ account.id }}"></a>
            {# Comm Edit URL #}
            <a class="pen comm-control comm-edit" 
               href="{% url 'comm_update' comm.uuid %}?account={{ account.id }}"></a>
        </span>
    </h5>
    <p class="co-item-date">on {{ comm.date }}</p>
    <p>{{ comm.notes }}</p>
</li>